sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
script:
  - case "$TRAVIS_NODE_VERSION" in
    4|5)
      tap test/node-syntax-test.js
      ;;
    *)
      npm run test
      ;;
    esac
  - npm run lint
